export const clientes = [
  {
    id: 1,
    name: "João Silva",
    contact: "João Silva",
    email: "joao.silva@gmail.com",
    phone: "(11) 99999-1111",
    city: "São Paulo, SP",
    segment: "Pessoa Física",
    orcamentos: 3,
    totalGasto: 3200,
    status: "ativo",
    score: 5,
  },
  {
    id: 2,
    name: "Transportadora Veloz",
    contact: "Carlos Neto",
    email: "carlos@transveloz.com",
    phone: "(11) 98888-2222",
    city: "São Paulo, SP",
    segment: "Frota/Transporte",
    orcamentos: 5,
    totalGasto: 12400,
    status: "ativo",
    score: 5,
  },
  {
    id: 3,
    name: "Maria Oliveira",
    contact: "Maria Oliveira",
    email: "maria.oliveira@hotmail.com",
    phone: "(21) 97777-3333",
    city: "Rio de Janeiro, RJ",
    segment: "Pessoa Física",
    orcamentos: 2,
    totalGasto: 1350,
    status: "ativo",
    score: 4,
  },
  {
    id: 4,
    name: "Auto Peças Central",
    contact: "Roberto Dias",
    email: "roberto@autopecascentral.com",
    phone: "(11) 96666-4444",
    city: "São Paulo, SP",
    segment: "Comércio Auto",
    orcamentos: 4,
    totalGasto: 8500,
    status: "ativo",
    score: 4,
  },
  {
    id: 5,
    name: "Pedro Almeida",
    contact: "Pedro Almeida",
    email: "pedro.almeida@outlook.com",
    phone: "(31) 95555-5555",
    city: "Belo Horizonte, MG",
    segment: "Pessoa Física",
    orcamentos: 1,
    totalGasto: 1800,
    status: "potencial",
    score: 3,
  },
  {
    id: 6,
    name: "Locadora AutoFlex",
    contact: "Marcos Leal",
    email: "marcos@autoflex.com",
    phone: "(11) 94444-6666",
    city: "São Paulo, SP",
    segment: "Locadora",
    orcamentos: 8,
    totalGasto: 22000,
    status: "ativo",
    score: 5,
  },
  {
    id: 7,
    name: "Ana Beatriz Ramos",
    contact: "Ana Beatriz",
    email: "anab.ramos@gmail.com",
    phone: "(41) 93333-7777",
    city: "Curitiba, PR",
    segment: "Pessoa Física",
    orcamentos: 1,
    totalGasto: 0,
    status: "inativo",
    score: 2,
  },
  {
    id: 8,
    name: "Concessionária Premium Motors",
    contact: "Fernando Costa",
    email: "fernando@premiummotors.com",
    phone: "(11) 92222-8888",
    city: "São Paulo, SP",
    segment: "Concessionária",
    orcamentos: 6,
    totalGasto: 15800,
    status: "ativo",
    score: 5,
  },
];
