import type { IProcesso } from "./types";

export const processos: IProcesso[] = [
  {
    id: "PROC-001",
    cliente: "João Silva",
    telefone: "(11) 99999-1111",
    servico: "Transferência de Veículo",
    tipoServico: "Transferência",
    veiculo: "Honda Civic 2022",
    placa: "ABC-1D23",
    status: "detran",
    dataEntrada: "15/01/2026",
    prazoFinal: "30/01/2026",
    diasRestantes: 3,
    responsavel: "RS",
    documentos: [
      { nome: "CRV Original", recebido: true },
      { nome: "ATPV-e assinado", recebido: true },
      { nome: "Comprovante de residência", recebido: true },
      { nome: "Laudo de vistoria", recebido: false },
    ],
    observacoes: "Aguardando retorno da vistoria agendada para 28/01",
    etapaAtual: 3,
    totalEtapas: 5,
  },
  {
    id: "PROC-002",
    cliente: "Transportadora Veloz",
    telefone: "(11) 98888-2222",
    servico: "Licenciamento de Frota (12 veículos)",
    tipoServico: "Licenciamento",
    veiculo: "Frota — 12 veículos",
    placa: "Diversos",
    status: "documentacao",
    dataEntrada: "18/01/2026",
    prazoFinal: "15/02/2026",
    diasRestantes: 19,
    responsavel: "AL",
    documentos: [
      { nome: "CRLVs anteriores", recebido: true },
      { nome: "Comprovantes de pagamento IPVA", recebido: false },
      { nome: "Laudos de vistoria", recebido: false },
      { nome: "Procuração", recebido: true },
    ],
    observacoes: "Cliente precisa enviar comprovantes de IPVA de 4 veículos",
    etapaAtual: 2,
    totalEtapas: 4,
  },
  {
    id: "PROC-003",
    cliente: "Pedro Almeida",
    telefone: "(31) 95555-5555",
    servico: "1º Emplacamento",
    tipoServico: "Emplacamento",
    veiculo: "Toyota Corolla Cross 2026",
    placa: "Pendente",
    status: "entrada",
    dataEntrada: "20/01/2026",
    prazoFinal: "10/02/2026",
    diasRestantes: 14,
    responsavel: "RS",
    documentos: [
      { nome: "Nota Fiscal do veículo", recebido: true },
      { nome: "RG / CPF proprietário", recebido: true },
      { nome: "Comprovante de residência", recebido: false },
      { nome: "GRV paga", recebido: false },
    ],
    observacoes: "Aguardando comprovante de residência do proprietário",
    etapaAtual: 1,
    totalEtapas: 6,
  },
  {
    id: "PROC-004",
    cliente: "Locadora AutoFlex",
    telefone: "(11) 94444-6666",
    servico: "Emplacamento + Vistoria (5 veículos)",
    tipoServico: "Emplacamento",
    veiculo: "Lote 5 veículos novos",
    placa: "Pendentes",
    status: "atrasado",
    dataEntrada: "05/01/2026",
    prazoFinal: "19/01/2026",
    diasRestantes: -8,
    responsavel: "CF",
    documentos: [
      { nome: "NFs dos veículos", recebido: true },
      { nome: "Contrato social", recebido: true },
      { nome: "Procuração", recebido: true },
      { nome: "GRVs pagas", recebido: true },
      { nome: "Laudos de vistoria", recebido: false },
    ],
    observacoes: "URGENTE — Vistoria reagendada 2x. Novo agendamento: 22/01",
    etapaAtual: 4,
    totalEtapas: 6,
  },
  {
    id: "PROC-005",
    cliente: "Maria Oliveira",
    telefone: "(21) 97777-3333",
    servico: "Licenciamento + Vistoria",
    tipoServico: "Licenciamento",
    veiculo: "VW Gol 2019",
    placa: "XYZ-9H87",
    status: "aguardando",
    dataEntrada: "12/01/2026",
    prazoFinal: "28/01/2026",
    diasRestantes: 1,
    responsavel: "AL",
    documentos: [
      { nome: "CRLV anterior", recebido: true },
      { nome: "Comprovante IPVA", recebido: true },
      { nome: "Laudo de vistoria", recebido: true },
      { nome: "Taxa de licenciamento", recebido: true },
    ],
    observacoes: "Documentação completa. Aguardando liberação DETRAN digital",
    etapaAtual: 4,
    totalEtapas: 5,
  },
  {
    id: "PROC-006",
    cliente: "Concessionária Premium Motors",
    telefone: "(11) 92222-8888",
    servico: "Transferência (2 veículos)",
    tipoServico: "Transferência",
    veiculo: "2 veículos seminovos",
    placa: "DEF-2G34 / GHI-5J67",
    status: "concluido",
    dataEntrada: "03/01/2026",
    prazoFinal: "17/01/2026",
    diasRestantes: 0,
    responsavel: "RS",
    documentos: [
      { nome: "CRVs originais", recebido: true },
      { nome: "ATPV-e assinados", recebido: true },
      { nome: "Vistorias", recebido: true },
      { nome: "CRVs novos emitidos", recebido: true },
    ],
    observacoes:
      "Processo finalizado. CRVs novos entregues ao cliente em 16/01",
    etapaAtual: 5,
    totalEtapas: 5,
  },
];
