import type { Task } from "./types";

export const initialTasks: Task[] = [
  {
    id: 1,
    title: "Agendar vistoria DETRAN — Auto Peças (3 veículos)",
    description: "Vistoria para emplacamento de 3 veículos novos",
    priority: "alta",
    assignee: "RS",
    due: "20/01",
    tag: "Vistoria",
    column: "todo",
  },
  {
    id: 2,
    title: "Dar entrada transferência — João Silva",
    description: "CRV assinado com firma reconhecida, aguardando ATPV-e",
    priority: "alta",
    assignee: "AL",
    due: "21/01",
    tag: "Transferência",
    column: "todo",
  },
  {
    id: 3,
    title: "Retirar CRLV digital — Maria Oliveira",
    description: "Licenciamento pago, aguardando liberação no sistema",
    priority: "média",
    assignee: "RS",
    due: "22/01",
    tag: "Licenciamento",
    column: "todo",
  },
  {
    id: 4,
    title: "Renovar licenciamento frota Transportadora Veloz",
    description: "12 veículos com vencimento em fevereiro",
    priority: "baixa",
    assignee: "CF",
    due: "25/01",
    tag: "Licenciamento",
    column: "todo",
  },
  {
    id: 5,
    title: "1º Emplacamento — Pedro Almeida",
    description: "NF do veículo entregue, aguardando placa Mercosul",
    priority: "alta",
    assignee: "RS",
    due: "19/01",
    tag: "Emplacamento",
    column: "progress",
  },
  {
    id: 6,
    title: "Vistoria cautelar — Locadora AutoFlex (5 veículos)",
    description: "Laudos de vistoria para seguro da frota",
    priority: "média",
    assignee: "AL",
    due: "20/01",
    tag: "Vistoria",
    column: "progress",
  },
  {
    id: 7,
    title: "2ª Via CRV — Ana Beatriz Ramos",
    description: "Solicitação protocolada, aguardando retorno DETRAN",
    priority: "média",
    assignee: "CF",
    due: "23/01",
    tag: "Documento",
    column: "progress",
  },
  {
    id: 8,
    title: "Transferência concluída — Concessionária Premium (2 veículos)",
    description: "CRVs novos emitidos e entregues ao cliente",
    priority: "alta",
    assignee: "RS",
    due: "18/01",
    tag: "Transferência",
    column: "done",
  },
  {
    id: 9,
    title: "Licenciamento pago — João Silva",
    description: "CRLV digital disponível no app",
    priority: "baixa",
    assignee: "AL",
    due: "17/01",
    tag: "Licenciamento",
    column: "done",
  },
  {
    id: 10,
    title: "Emplacamento finalizado — Auto Peças (lote anterior)",
    description: "Placas instaladas e documentos entregues",
    priority: "média",
    assignee: "CF",
    due: "16/01",
    tag: "Emplacamento",
    column: "done",
  },
];
